import 'package:chatgpt_clone/types.dart';
import 'package:chatgpt_clone/update.dart';
import 'package:flutter/material.dart';

import 'ChatFrame.dart';
import 'Decoupler.dart';

Decoupler<TProps, String, String, String> decoupler =
    Decoupler(initialState: TProps(), update: update);

void main() {
  decoupler.registerIOHandler((state) =>
      runApp(FigmaToCodeApp(input: state.input, messages: state.messages)));

  decoupler.init();
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  final String input;
  final List<TMessage> messages;

  const FigmaToCodeApp(
      {super.key, required this.input, required this.messages});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: App(messages: messages),
      ),
    );
  }
}

class App extends StatelessWidget {
  final List<TMessage> messages;

  const App({super.key, required this.messages});

  @override
  Widget build(
    BuildContext context,
  ) {
    return ChatFrame(messages: messages, disabled: false, input: '');
  }
}
